# Official documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0
  binary: jcli
  goarch:
    - amd64
    - arm64
  goos:
    - windows
    - linux
    - darwin
  ignore:
    - goos: windows
      goarch: arm
    - goos: windows
      goarch: arm64
    - goos: darwin
      goarch: arm
  ldflags:
    - -X github.com/linuxsuren/cobra-extension/version.version={{.Version}}
    - -X github.com/linuxsuren/cobra-extension/version.commit={{.ShortCommit}}
    - -X github.com/linuxsuren/cobra-extension/version.date={{.Date}}
    - -w
    - -s
dist: release
archives:
- name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"
  format_overrides:
    - goos: windows
      format: zip
  files:
    - README.md
    - README-zh.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next-{{.ShortCommit}}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
