name: jcli
version: v0.0.25
summary: Jenkins CLI allows you manage your Jenkins in an easy way.
description: |
  Jenkins CLI allows you manage your Jenkins in an easy way. No matter if you're a plugin

confinement: devmode
base: core18

parts:
  jcli:
    plugin: dump
    source: .
    organize:
      jcli: bin/linux
apps:
  jcli:
    command: bin/linux/jcli
