name: Pull Request Clean

on:
  pull_request:
    types: [closed]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Build
        run: |
          pr=$(echo $GITHUB_REF | sed 's/refs\/pull\///g' | sed 's/\/merge//g')
          curl -ulinuxsuren:${{ secrets.BINTRAY_TOKEN }} -X DELETE https://api.bintray.com/packages/jenkins-zh/generic/jenkins-cli/versions/pr-$pr
