name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-20.04
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_SECRETS }}
